FROM debian:bullseye-slim

# Default ENV
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Base system
RUN apt-get update && apt-get install -y --no-install-recommends \
        bash \
        jq \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio

ENTRYPOINT /bin/bash